name: Build and Release
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build app
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clone repo
        uses: actions/checkout@v3
        
      - name: Create file
        run: cat /home/runner/work/AniShare-Android-Client/AniShare-Android-Client/app/google-services.json | base64
        
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/AniShare-Android-Client/AniShare-Android-Client/app/google-services.json
        
      - name: Set execution flag for gradlew
        run: chmod +x gradlew

      - name: Build app
        run: ./gradlew assembleRelease

      # Sign APK and create release for tags

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          mv ${{ steps.sign_app.outputs.signedReleaseFile }} anishare-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum anishare-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV
      - name: Extract release notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: AniShare ${{ env.VERSION_TAG }}
          body: |
            ${{ steps.extract_release_notes.outputs.release_notes }}
            ---
            ### Checksums
            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
          files: |
            anishare-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
