name: Tag Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  tag_release:
    if: github.event.pull_request.merged == true && ${{github.event.pull_request.title == 'v* into main'}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Setup release information
        #get version name from app_versions.gradle file (5.6.2)
        run: |
          versionName=`sed '2q;d' app_versions.gradle | cut -d "=" -f2 | xargs`
          export VERSION_NAME=$versionName
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
      - name: Create Tag
        run: git tag v${{ env.VERSION_NAME }}
      - name: Push Tag
        run: git push origin v${{ env.VERSION_NAME }}
